/*
 * This source file was generated by the Gradle 'init' task
 */
package com.assignment;

import javax.swing.JOptionPane;

public class App {
    
    public static void main(String[] args) {
        /* getting water in kilograms */
        String massInput = JOptionPane.showInputDialog("Enter the amount of water in kilograms:");
        double waterMass = Double.parseDouble(massInput);

        /* getting initial temperature in Celsius */
        String initialTempInput = JOptionPane.showInputDialog("Enter the initial temperature in Celsius:");
        double initialTemperature = Double.parseDouble(initialTempInput);

        /* getting final temperature in Celsius */
        String finalTempInput = JOptionPane.showInputDialog("Enter the final temperature in Celsius:");
        double finalTemperature = Double.parseDouble(finalTempInput);
        /* calculating energy in Joules */
        double energyJoules = waterMass * (finalTemperature - initialTemperature) * 4184;
        /* displaying the result */
        String message = "The energy needed is " + energyJoules + " Joules";
        JOptionPane.showMessageDialog(null, message, "Energy Calculation Result", JOptionPane.INFORMATION_MESSAGE);
    }
}
